disabled_rules: # rule identifiers to exclude from running
  - notification_center_detachment
  - line_length
  - trailing_whitespace
  - todo
  - vertical_parameter_alignment
  - switch_case_alignment
  - cyclomatic_complexity
  
opt_in_rules: # some rules are only opt-in
  - closure_body_length
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - no_fallthrough_only
  - fatal_error_message
  - first_where
  - function_default_parameter_at_end
  - function_parameter_count
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - modifier_order
  - multiple_closures_with_trailing_closure
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - static_operator
  - toggle_bool
  - unavailable_function
  - untyped_error_in_catch
  - unused_optional_binding
  - unused_private_declaration
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - yoda_condition
included: # paths to include during linting. `--path` is ignored if present.
  - CSVReader
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - CSVReader/Resources
  - CSVReader/"Supporting Files".swift
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

weak_delegate:
  severity: error

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
